version: '3'
services:
  rea:
    image: aiktb/rea:latest
    restart: unless-stopped
    ports:
      - '8083:8083'
    networks:
      - default
    volumes:
      - ./data/about.md:rea/docs/about.md
      - ./data/archive.md:rea/docs/archive.md
      - ./data/links.md:rea/docs/links.md
      - ./data/posts:rea/docs/posts
networks:
  default:
